/*
 * MicroPacControllerMan — firmware entry point (called from the CubeMX main()).
 *
 * M1 brought up the toolchain and the OTT reset framework. M2 (Board Bring-Up)
 * moved off the register-level BSP onto the STM32 HAL: hardware init (clock,
 * GPIO, LPUART1, I2C1, SPI1) is generated by STM32CubeMX and runs in main()
 * before app_main() is entered. app_main() owns the application: the OTT reset
 * flow, the boot banner and the nominal super-loop.
 *
 * Note: the on-board LED (LD2/PA5) was dropped in M2 — PA5 is needed as SPI1_SCK
 * for the display, and a pin can only have one function. See the milestone doc.
 */
#include "app_main.h"

#include "ott.h"
#include "uart.h"

void app_main(void)
{
    /* Pins + peripherals are already up (CubeMX MX_*_Init). uart_init() only
     * pins the VCP console baud to 115200, the rate the test harness expects. */
    uart_init();

    ott_execute_pending(); /* if an `ott` command scheduled a test + reset, run it now */

    /* Boot banner — a known, readable line for the harness (VT-INT-002). */
    uart_write("\r\nMicroPacControllerMan booted (M2 HAL bring-up). Type 'ott' for tests.\r\n");

    ott_init(); /* set up the EmbeddedCli-based OTT console */

    for (;;) {
        ott_poll(); /* service the OTT command line */
    }
}
