/*
 * MicroPacControllerMan — firmware entry point (called from the CubeMX main()).
 *
 * M1 brought up the toolchain, blinky and the OTT reset framework. M2 (Board
 * Bring-Up) moved off the register-level BSP onto the STM32 HAL: hardware init
 * (clock, GPIO, LPUART1, I2C1) is generated by STM32CubeMX and runs in main()
 * before app_main() is entered. app_main() owns the application: the OTT reset
 * flow, the boot banner and the nominal super-loop.
 */
#include "app_main.h"

#include "led.h"
#include "ott.h"
#include "systick.h"
#include "uart.h"

void app_main(void)
{
    /* Pins + peripherals are already up (CubeMX MX_*_Init). uart_init() only
     * pins the VCP console baud to 115200, the rate the test harness expects. */
    uart_init();

    ott_execute_pending(); /* if an `ott` command scheduled a test + reset, run it now */

    led_init(); /* no-op: LD2/PA5 is configured as an output by MX_GPIO_Init() */

    /* Boot banner — a known, readable line for the harness (VT-INT-002). */
    uart_write("\r\nMicroPacControllerMan booted (M2 HAL bring-up). Type 'ott' for tests.\r\n");

    ott_init(); /* set up the EmbeddedCli-based OTT console */

    uint32_t last_toggle = 0;
    for (;;) {
        /* nominal ~1 Hz blink, non-blocking */
        if ((millis() - last_toggle) >= 500U) {
            last_toggle = millis();
            led_toggle();
        }
        /* service the OTT command line */
        ott_poll();
    }
}
