#!/usr/bin/env bash
#
# Apply the project's coding standard (NFR-102) to the source tree with clang-format.
# Run it from anywhere.
#
#   ./format.sh                 # format every source file in place
#   ./format.sh --check         # change nothing; list what is unformatted, exit 1 if any
#   ./format.sh --diff          # change nothing; print the diff that --check would fix
#   ./format.sh App/game        # limit to a path (file or directory), repeatable
#   ./format.sh --staged        # format only what is staged in git, and re-stage it
#
# `./dev.sh format` and the CMake `format` / `format-check` targets are this script; it is
# the single definition of what "formatted" means. The pre-commit hook is installed from
# `./dev.sh install-hook`, because it also runs the unit tests and so is more than a
# formatting concern; `--staged` is the part of it that lives here.
#
# The style is Firmware/.clang-format, vendored from https://github.com/MaxLell/c-code-style.
# It is the standard itself, so it is not edited here — a change to it goes via a PR to that
# repo, with the owner's prior approval.
#
# What is deliberately NOT formatted:
#
#   ThirdParty/  — not our code. The STM32CubeMX export is regenerated by the GUI and
#                  EmbeddedCli is vendored upstream; reformatting either would turn every
#                  future update into a merge conflict for no benefit.
#   build*/      — generated.
#
# A block that must keep its hand-made shape is guarded in the source with
# `/* clang-format off */` … `/* clang-format on */` — see the maze table in
# App/playfield/playfield.c, where one row per line *is* the maze.
set -euo pipefail

cd "$(dirname "$0")"

# The layers of [03 §3.9]. A new top-level source folder has to be added here.
readonly SOURCE_ROOTS=(App Bsp Drivers Services Test)
readonly MINIMUM_MAJOR_VERSION=14

red() { printf '\033[1;31m%s\033[0m\n' "$*"; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
step() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

require_clang_format() {
    if ! command -v clang-format >/dev/null 2>&1; then
        red "clang-format not found. Install it with: sudo apt-get install -y clang-format"
        exit 127
    fi

    local major
    major=$(clang-format --version | grep -oE '[0-9]+' | head -1)

    # Older releases do not understand every key in the vendored style and would silently
    # format to something else, which is worse than not formatting at all.
    if [ "$major" -lt "$MINIMUM_MAJOR_VERSION" ]; then
        red "clang-format $major is too old; this style needs $MINIMUM_MAJOR_VERSION or newer."
        exit 1
    fi
}

# Every .c/.h under the given paths, or under the source roots when none were given.
collect_files() {
    local -a roots=("$@")

    if [ ${#roots[@]} -eq 0 ]; then
        roots=("${SOURCE_ROOTS[@]}")
    fi

    find "${roots[@]}" \( -name '*.c' -o -name '*.h' \) -type f \
        -not -path '*/ThirdParty/*' -not -path '*/build*/*' | sort
}

format_in_place() {
    local -a files
    mapfile -t files < <(collect_files "$@")

    step "Formatting ${#files[@]} files"

    local changed=0 file
    for file in "${files[@]}"; do
        # The same question `check_only` asks, asked the same way on purpose: "is the formatted
        # output different from the file". It used to ask clang-format for a replacement list and
        # `grep -q` it, which **silently skipped every file needing a large reformat** — `grep -q`
        # exits at the first match, clang-format dies of SIGPIPE writing the rest, and under
        # `set -o pipefail` the pipeline then reports failure, which read as "nothing to do". Small
        # diffs fit in the 64 kB pipe buffer and worked; big ones did not. So `format.sh` reported a
        # clean tree while `format.sh --check` rejected it, which is how it was found.
        if clang-format --style=file "$file" | diff -q "$file" - >/dev/null; then
            continue
        fi

        clang-format --style=file -i "$file"
        echo "  $file"
        changed=$((changed + 1))
    done

    if [ "$changed" -eq 0 ]; then
        green "Already formatted — nothing to do."
    else
        green "Reformatted $changed of ${#files[@]} files."
    fi
}

# --check / --diff. Reports rather than rewrites, which is what CI wants: a build that
# fails on unformatted code, without a build that edits the working tree behind your back.
check_only() {
    local mode=$1
    shift

    local -a files
    mapfile -t files < <(collect_files "$@")

    local -a offenders=()
    local file
    for file in "${files[@]}"; do
        if clang-format --style=file "$file" | diff -q "$file" - >/dev/null; then
            continue
        fi

        offenders+=("$file")

        if [ "$mode" = "--diff" ]; then
            clang-format --style=file "$file" | diff -u --label "$file" --label "$file (formatted)" "$file" - || true
        fi
    done

    if [ ${#offenders[@]} -eq 0 ]; then
        green "All ${#files[@]} files match the coding standard."
        return 0
    fi

    red "${#offenders[@]} of ${#files[@]} files are not formatted:"
    printf '  %s\n' "${offenders[@]}"
    echo
    echo "Fix them with: $(basename "$0")"

    return 1
}

# Only what is about to be committed, so a formatting pass never lands mixed into an
# unrelated change.
format_staged() {
    local -a files
    mapfile -t files < <(git -C .. diff --cached --name-only --diff-filter=ACMR \
        | grep -E '^Firmware/.*\.[ch]$' | grep -vE '^Firmware/(ThirdParty|build)' | sed 's|^Firmware/||' || true)

    if [ ${#files[@]} -eq 0 ]; then
        return 0
    fi

    local changed=0 file
    for file in "${files[@]}"; do
        [ -f "$file" ] || continue

        if clang-format --style=file "$file" | diff -q "$file" - >/dev/null; then
            continue
        fi

        clang-format --style=file -i "$file"
        git -C .. add "Firmware/$file"
        echo "  formatted $file"
        changed=$((changed + 1))
    done

    [ "$changed" -gt 0 ] && green "Formatted and re-staged $changed file(s)."

    return 0
}

require_clang_format

case "${1:-}" in
    --check | --diff)
        mode=$1
        shift
        check_only "$mode" "$@"
        ;;
    --staged)
        format_staged
        ;;
    -h | --help)
        sed -n '2,30p' "$0" | sed 's|^# \{0,1\}||'
        ;;
    *)
        format_in_place "$@"
        ;;
esac
